name: easy_font_loader
description: Load TTF files form network or assets.
version: 0.0.2
homepage: https://github.com/camrongiuliani/easy_font_loader

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.0
  stash: ^4.4.1
  stash_sembast_web: ^4.4.1
  http: ^0.13.5
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
